import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight, Clock3, ExternalLink, LayoutTemplate, MessageCircle, MonitorSmartphone, MousePointerClick, ShieldCheck, Sparkles, Zap } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });

const whatsappNumber = "5582988642056";
const whatsappLink = (message: string) => `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

const projects = [
  { title: "Aurora Clínica", type: "Site institucional · Conceito", description: "Site moderno para apresentar serviços, transmitir confiança e facilitar o agendamento.", solution: "Estrutura clara, informações objetivas e CTA para contato.", tone: "from-sky-100 via-cyan-50 to-white", icon: "✦" },
  { title: "Noma Studio", type: "Landing page · Conceito", description: "Landing page criada para apresentar um serviço de forma visual e levar o visitante à ação.", solution: "Headline direta, benefícios bem organizados e CTA estratégico.", tone: "from-violet-100 via-fuchsia-50 to-white", icon: "N" },
  { title: "Brava Móveis", type: "Site comercial · Conceito", description: "Catálogo digital simples para mostrar produtos e receber pedidos de orçamento pelo WhatsApp.", solution: "Produtos em destaque, navegação simples e contato sem fricção.", tone: "from-amber-100 via-orange-50 to-white", icon: "B" },
  { title: "Orbe Contábil", type: "Site profissional · Conceito", description: "Presença digital enxuta para um escritório que precisa passar profissionalismo desde o primeiro acesso.", solution: "Serviços, diferenciais e contato organizados em uma experiência objetiva.", tone: "from-emerald-100 via-teal-50 to-white", icon: "O" },
];

const services = [
  { icon: LayoutTemplate, title: "Landing pages", text: "Páginas objetivas para divulgar serviços, ofertas e campanhas." },
  { icon: MonitorSmartphone, title: "Sites profissionais", text: "Sites para empresas e profissionais que querem uma presença digital de verdade." },
  { icon: MousePointerClick, title: "Sites para negócios", text: "Estruturas simples para apresentar o negócio e transformar visitas em contatos." },
];

const steps = [
  ["01", "Você me conta a ideia", "Entendo seu negócio e o que você espera do site."],
  ["02", "Definimos a estrutura", "Organizo as informações para o visitante não se perder."],
  ["03", "Eu desenvolvo", "Crio o site com foco em visual, velocidade e celular."],
  ["04", "Você revisa", "Ajustamos os detalhes antes de publicar."],
  ["05", "Seu site vai ao ar", "Tudo pronto para você começar a divulgar."],
];

function Index() {
  const contactMessage = "Olá, Wendel! Vi seu portfólio e quero conversar sobre um site para o meu negócio.";
  return (
    <main className="min-h-screen overflow-x-hidden bg-[#f7f8fa] text-[#101828] selection:bg-[#111827] selection:text-white">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-900/5 bg-[#f7f8fa]/85 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 lg:px-8">
          <a href="#inicio" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#111827] text-sm text-white">W</span><span>Wendel<span className="text-slate-400">.</span></span></a>
          <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#projetos" className="transition hover:text-slate-950">Projetos</a><a href="#servicos" className="transition hover:text-slate-950">Serviços</a><a href="#processo" className="transition hover:text-slate-950">Como funciona</a></nav>
          <a href={whatsappLink(contactMessage)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#111827] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-slate-800 active:scale-95"><MessageCircle size={16} /> Falar comigo</a>
        </div>
      </header>

      <section id="inicio" className="relative mx-auto max-w-6xl px-5 pb-20 pt-36 lg:px-8 lg:pb-28 lg:pt-44">
        <div className="pointer-events-none absolute left-1/2 top-16 -z-0 h-72 w-72 -translate-x-1/2 rounded-full bg-blue-200/30 blur-3xl animate-pulse-soft" />
        <div className="relative z-10 max-w-4xl animate-fade-up">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-slate-900/10 bg-white/70 px-3.5 py-2 text-xs font-semibold text-slate-600 shadow-sm"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500" /> Disponível para novos projetos</div>
          <h1 className="max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-0.045em] text-slate-950 sm:text-6xl lg:text-7xl">Seu negócio merece um site que passe confiança.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">Eu sou Wendel, desenvolvedor web. Crio sites profissionais, rápidos e pensados para fazer seu negócio ser levado a sério — sem preço de agência.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={whatsappLink(contactMessage)} target="_blank" rel="noreferrer" className="group inline-flex items-center justify-center gap-2 rounded-xl bg-[#111827] px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-slate-900/10 transition hover:-translate-y-1 hover:shadow-xl active:scale-[.98]">Quero um site para meu negócio <ArrowRight size={17} className="transition group-hover:translate-x-1" /></a><a href="#projetos" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-900/10 bg-white px-6 py-3.5 text-sm font-semibold text-slate-700 transition hover:-translate-y-0.5 hover:bg-slate-50">Ver projetos <ChevronRight size={17} /></a></div>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Zap size={15} /> Sites rápidos</span><span className="inline-flex items-center gap-2"><MonitorSmartphone size={15} /> 100% responsivos</span><span className="inline-flex items-center gap-2"><ShieldCheck size={15} /> Atendimento direto</span></div>
        </div>
      </section>

      <section className="border-y border-slate-900/5 bg-white"><div className="mx-auto grid max-w-6xl grid-cols-1 divide-y divide-slate-900/5 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 lg:px-8">{[["1 ano", "de experiência"], ["R$ 100–500", "faixa inicial"], ["Direto com o dev", "sem intermediários"]].map(([value, label]) => <div key={value} className="px-5 py-7 text-center transition hover:bg-slate-50 sm:px-8"><p className="text-xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div></section>

      <section id="projetos" className="mx-auto max-w-6xl px-5 py-24 lg:px-8 lg:py-32">
        <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end animate-fade-up"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-slate-400">Projetos</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Quatro conceitos para mostrar o que eu posso criar.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Projetos fictícios demonstrativos enquanto novos trabalhos entram no portfólio.</p></div>
        <div className="mt-12 grid gap-6 md:grid-cols-2">{projects.map((project, index) => <article key={project.title} className="group overflow-hidden rounded-3xl border border-slate-900/8 bg-white shadow-[0_12px_40px_-25px_rgba(15,23,42,.25)] transition duration-500 hover:-translate-y-2 hover:shadow-[0_28px_60px_-28px_rgba(15,23,42,.35)] animate-fade-up" style={{ animationDelay: `${index * 100}ms` }}><div className={`relative h-52 overflow-hidden bg-gradient-to-br ${project.tone}`}><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-white/50 blur-2xl transition duration-700 group-hover:scale-150" /><div className="absolute inset-6 rounded-2xl border border-white/70 bg-white/75 p-5 shadow-xl backdrop-blur transition duration-500 group-hover:scale-[1.02]"><div className="flex items-center justify-between border-b border-slate-900/8 pb-3"><div className="flex gap-1.5"><i className="h-2 w-2 rounded-full bg-slate-300" /><i className="h-2 w-2 rounded-full bg-slate-200" /><i className="h-2 w-2 rounded-full bg-slate-100" /></div><span className="text-[9px] font-bold uppercase tracking-widest text-slate-400">conceito</span></div><div className="mt-5 flex items-end justify-between"><div><div className="h-2 w-24 rounded bg-slate-900/15" /><div className="mt-2 h-2 w-36 rounded bg-slate-900/7" /><div className="mt-5 h-7 w-20 rounded-lg bg-slate-900/10" /></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-lg font-bold text-white transition duration-500 group-hover:rotate-6">{project.icon}</span></div></div></div><div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{project.type}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{project.title}</h3></div><span className="mt-1 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-500">DEMO</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{project.description}</p><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Abordagem</p><p className="mt-1.5 text-sm font-medium leading-5 text-slate-700">{project.solution}</p></div><a href={whatsappLink(`Olá, Wendel! Gostei do conceito ${project.title} e quero um site parecido para meu negócio.`)} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-900 transition group-hover:gap-2.5">Quero algo assim <ExternalLink size={14} /></a></div></article>)}</div>
      </section>

      <section id="servicos" className="bg-[#111827] text-white"><div className="mx-auto max-w-6xl px-5 py-24 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-slate-400">O que eu faço</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Sites que fazem seu negócio parecer profissional.</h2><p className="mt-5 leading-7 text-slate-400">Você não precisa de uma plataforma gigante. Precisa de um site que explique seu negócio, passe confiança e facilite o próximo contato.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{services.map((service, index) => { const Icon = service.icon; return <div key={service.title} className="rounded-3xl border border-white/10 bg-white/[.04] p-6 transition duration-500 hover:-translate-y-2 hover:bg-white/[.07] animate-fade-up" style={{ animationDelay: `${index * 100}ms` }}><Icon size={22} className="text-slate-300" /><h3 className="mt-6 text-lg font-semibold">{service.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{service.text}</p></div> })}</div></div></section>

      <section id="processo" className="mx-auto max-w-6xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-slate-400">Como funciona</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Sem complicação.</h2><p className="mt-5 leading-7 text-slate-500">Você fala o que precisa. Eu cuido de transformar isso em um site pronto para apresentar seu negócio.</p></div><div className="divide-y divide-slate-900/8">{steps.map(([number, title, text]) => <div key={number} className="group flex gap-5 py-6 first:pt-0 last:pb-0"><span className="font-mono text-xs text-slate-400 transition group-hover:text-slate-950">{number}</span><div><h3 className="font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div>)}</div></div></section>

      <section className="border-y border-slate-900/5 bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-3 lg:px-8"><div className="flex gap-4"><Check className="shrink-0" size={20} /><div><h3 className="font-semibold">Preço acessível</h3><p className="mt-1 text-sm text-slate-500">Projetos a partir de R$100, conforme a necessidade.</p></div></div><div className="flex gap-4"><Clock3 className="shrink-0" size={20} /><div><h3 className="font-semibold">Prazo combinado</h3><p className="mt-1 text-sm text-slate-500">Você sabe o que esperar antes de começarmos.</p></div></div><div className="flex gap-4"><ShieldCheck className="shrink-0" size={20} /><div><h3 className="font-semibold">Contato direto</h3><p className="mt-1 text-sm text-slate-500">Você conversa diretamente com quem desenvolve.</p></div></div></div></section>

      <section id="contato" className="mx-auto max-w-6xl px-5 py-24 text-center lg:px-8 lg:py-32"><Sparkles className="mx-auto text-slate-400" size={24} /><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Seu próximo cliente pode estar procurando por você agora.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-7 text-slate-500">Vamos colocar seu negócio na internet com um site profissional, responsivo e dentro do seu orçamento.</p><a href={whatsappLink(contactMessage)} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#111827] px-7 py-4 text-sm font-semibold text-white shadow-lg shadow-slate-900/10 transition hover:-translate-y-1 hover:shadow-xl active:scale-95">Falar com Wendel <ArrowRight size={17} /></a><p className="mt-5 text-xs text-slate-400">WhatsApp · R$100–500 · Atendimento direto</p></section>

      <footer className="border-t border-slate-900/5 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© {new Date().getFullYear()} Wendel.</span><span>Sites profissionais para negócios.</span></div></footer>
      <a href={whatsappLink(contactMessage)} target="_blank" rel="noreferrer" aria-label="Falar com Wendel pelo WhatsApp" className="fixed bottom-5 right-5 z-50 grid h-14 w-14 place-items-center rounded-full bg-[#111827] text-white shadow-xl shadow-slate-900/20 transition hover:-translate-y-1 hover:scale-105 active:scale-95 sm:bottom-7 sm:right-7"><MessageCircle size={23} /></a>
    </main>
  );
}
